DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER(
  ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL
);

INSERT INTO MEMBER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Jessica', 'Campbell', 'jcampbell2i@cpanel.net'); 
INSERT INTO MEMBER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bob', 'Marley', 'bob.marley@google.com'); 
INSERT INTO MEMBER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Tom', 'Brady', 'tom.brady@expat.net'); 
