package com.sams.merch.engenable.memberservice.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "MEMBER")
@Getter
@NoArgsConstructor
public class Member {
    
    @Id
    @Column(name = "ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description="Member ID which is unique to a member. Is generated by service on creation.", example="1001")
    private Long id;

    @Column(name = "FIRST_NAME")
    @Schema(description = "First Name of Member", example = "Jessica", required = true, maxLength = 50)
    @NotBlank(message = "First Name is required for a member.")
    private String firstName;

    @Column(name = "LAST_NAME")
    @Schema(description = "Last Name of Member", example = "Campbell", required = true, maxLength = 50)
    @NotBlank(message = "Last Name is required for a member.")
    private String lastName;

    @Column(name = "EMAIL")
    @Schema(description = "Email address of Member", example = "jcampbell2i@cpanel.net", required = true, maxLength = 50)
    @Pattern(regexp = ".+@.+\\..+", message = "Please provide a valid email address")
    @NotBlank(message = "Email is required for a member.")
    private String email;

}
